// packages/react/app/src/App.tsx
import React, {useState} from 'react'
import {useForm, FieldArray} from '@typesafe-form/react'
import z from 'zod'


const validator = z.object({
  persons: z.array(z.object({
    name: z.string()
  })),
  meta: z.string()
})

const App = () => {
  const {handleSubmit, register, errors, reset, registerArray} = useForm({
    onSubmit: (value) => {
      reset()
      console.log(value)
    },
    validator
  })

  const [selection, setSelection] = useState<number>()

  const select = (index: number, swap: (id1: number, id2: number) => void) => () => {
    if (selection === undefined) {
      setSelection(index)
      return
    }
    swap(selection, index)
    setSelection(undefined)
  }

  return <main>
    <h1 className="text-3xl">Input Testing</h1>
    <div className="p-3"/>
    <form onSubmit={handleSubmit} onReset={reset} className="flex flex-col items-start gap-4">
      {errors.persons.message}
      <FieldArray {...registerArray('persons')} render={persons => {
        return <>
          <div className="flex gap-2">
            <button type="button" onClick={() => persons.append()}>Append Person</button>
            <button type="button" onClick={() => persons.prepend()}>Prepend Person</button>
          </div>
          {persons.items.map((person, index) => {
            return <React.Fragment key={person.id}>
              <div className="flex gap-4 items-center">
                <label htmlFor={`persons.${index}.name`} className="test-lg">Name</label>
                <input type="text" id={`persons.${index}.name`} {...register(`persons.${index}.name`)}/>
                <button type="button" onClick={() => person.remove()}>Delete</button>
                <button type="button" onClick={() => person.append()}>Append</button>
                <button type="button" onClick={() => person.prepend()}>Prepend</button>
                <button type="button" onClick={() => persons.insert(index)}>Insert</button>
                <button type="button" className={`${selection === index ? '!bg-green-700' : ''}`} onClick={select(index, persons.swap)}>Select</button>
              </div>
              {errors.persons.items[index]?.name?.message}
            </React.Fragment>
          })}
        </>
      }}/>
      <input type="text" {...register('meta')}/>
      {errors.meta?.message}
      <div className="flex gap-2">
        <button>Submit</button>
        <button type="reset">Reset</button>
      </div>
    </form>
  </main>
}

export default App

// packages/svelte/app/src/App.svelte
<script lang="ts">
  import {createForm} from '@typesafe-form/svelte'
  import z from 'zod'

  const {handleSubmit, register, reset, errors} = createForm({
    validator: z.object({
      test: z.string(),
      lol: z.object({
        house: z.string()
      })
    }),
    onSubmit: value => {
      console.log(value)
      reset()
    }
  })
</script>

<main>
  <h1 class="text-3xl">Input Testing</h1>
  <div class="p-3"/>
  <form novalidate on:submit={handleSubmit} on:reset={reset} class="flex flex-col items-start gap-4">
    <div class="flex items-center gap-2">
      <label for="test" class="text-lg">Test</label>
      <input type="text" id="test" use:register={{name: 'test'}}>
    </div>
    {#if $errors.test}
      {$errors.test.message}
    {/if}
    <div class="flex items-center gap-2">
      <label for="lol" class="text-lg">Lol</label>
      <input type="text" id="lol" use:register={{name: 'lol.house'}}>
    </div>
    {#if $errors.lol.house}
      {$errors.lol.house.message}
    {/if}
    <button>Submit</button>
  </form>
</main>
